apiVersion: v2
name: meetoria
description: Meetoria - Multi-tenant appointment scheduling SaaS
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "19.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: rabbitmq
    version: "14.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
